import piece
kingw = piece.king("white", 5, 8 )
queenw = piece.queen("white", 4, 8)
rookw1 = piece.rook("white", 1, 8)
rookw2 = piece.rook("white", 8, 8)
knightw1 = piece.knight("white", 2, 8)
knightw2 = piece.knight("white", 7, 8)
bishopw1 = piece.bishop("white", 3, 8)
bishopw2 = piece.bishop("white", 6, 8)
pawnw1 = piece.pawn("white", 1, 7)
pawnw2 = piece.pawn("white", 2, 7)
pawnw3 = piece.pawn("white", 3, 7)
pawnw4 = piece.pawn("white", 4, 7)
pawnw5 = piece.pawn("white", 5, 7)
pawnw6 = piece.pawn("white", 6, 7)
pawnw7 = piece.pawn("white", 7, 7)
pawnw8 = piece.pawn("white", 8, 7)
kingb = piece.king("black", 5, 1 )
queenb = piece.queen("black", 4, 1)
rookb1 = piece.rook("black", 1, 1)
rookb2 = piece.rook("black", 8, 1)
knightb1 = piece.knight("black", 2, 1)
knightb2 = piece.knight("black", 7, 1)
bishopb1 = piece.bishop("black", 3, 1)
bishopb2 = piece.bishop("black", 6, 1)
pawnb1 = piece.pawn("black", 1, 2)
pawnb2 = piece.pawn("black", 2, 2)
pawnb3 = piece.pawn("black", 3, 2)
pawnb4 = piece.pawn("black", 4, 2)
pawnb5 = piece.pawn("black", 5, 2)
pawnb6 = piece.pawn("black", 6, 2)
pawnb7 = piece.pawn("black", 7, 2)
pawnb8 = piece.pawn("black", 8, 2)
pawnw1.x = 0
pawnw1.y = -1
pawnw1.movecheck()
print(pawnw1.currentx, pawnw1.currenty)

